from math import sqrt

# simulation setup
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 640
MAP_WIDTH = SCREEN_WIDTH * 4
MAP_HEIGHT = SCREEN_HEIGHT * 4
FPS = 30
DRAG_COEFFICIENT = 1
R_NORM = sqrt(MAP_WIDTH * MAP_WIDTH + MAP_HEIGHT * MAP_HEIGHT) / 2

# initial conditions
INIT_ENERGY_RESERVE = 1000 # must be larger than sum of initial organism and food energy
INIT_POP_SIZE = 10
INIT_NUM_FOOD = 100
NUM_DARK_MATTER = 50
INIT_ORGANISM_SIZE = 0.2
INIT_ORGANISM_STRENGTH = 10
INIT_ORGANISM_AGILITY = 10

# max/min values
MAX_POP_SIZE = 100
MAX_FOOD = 100
MIN_ORGANISM_SIZE = 0.2
MAX_ORGANISM_SIZE = 1